### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#1]
Suggestion: Arne's optimizer uses `GPL-3.0-or-later`. I think that's a good choice. :)

**Comment by dariogoetz** [comment]
The individual crates contain a license in their Cargo.toml. Is a "top-level" license required as well?

**Comment by Glitchy-Tozier** [comment]
I'm not 100% sure whether it's required, but it'd be a nice touch. This way, GitHub will actually show the license in your project's about-section:
Example from https://github.com/Glitchy-Tozier/Revolve-keyboard-layout:
![image](https://user-images.githubusercontent.com/59611881/140303946-677849f4-50cf-48ad-b834-43566cdce21f.png)

**Comment by dariogoetz** [comment]
I added a license from GitHub's template. This now looks like GPL-3.0. How can I specify the "-or-later" part?

**Comment by Glitchy-Tozier** [comment]
I *think* the default is `-or-later`. Looking at [this](https://spdx.org/licenses/GPL-3.0-or-later.html), your license seems about the same.

**Comment by dariogoetz** [comment]
Perfect. Thanks for the suggestion. I'll close this now.
