### ISSUE TITLE
Rearrange folders?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#11]
A couple of random thoughts:
- Due to recent changes the folder "layout optimization" seems to have a sub-optimal title. I suggest hinting at the fact that all it does is contain `common.rs`.
- By now there are quite a few optimization-folders, and there might be more to come. I feel like moving all of them into some shared directory would be a good idea. (maybe we should call _that_ place "`layout optimization`")
- Moving all website-folders into some shared space would clean up the place.

**Comment by dariogoetz** [comment]
The webui crates are now located in the `webui` directory. The optimization crates are now in `layout_optimization`. Also, the optimization crate containing the `common` module is now called `layout_optimization_common`.

**Comment by Glitchy-Tozier** [comment]
Nice job!
