### ISSUE TITLE
Re-test all layouts in https://keyboard-layout-optimizer.herokuapp.com/ every week

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#12]
Seeing as how our criteria change every now and then, it would be a good idea to make the website re-test all uploaded Layouts. Otherwise, that website would default to being a collection of found layouts with outdated scores. Which, unfortunately, wouldn't be very helpful.

(As an example, the layout `,so.xvdcljqßzaeiubtnrgyäöhüpfmwk` achieves a different score on both pages)

**Comment by dariogoetz** [comment]
Take a look at the reeval endpoint. That should do what you have in mind.

I am a little surprised, though, that there are different scores. I do not recall changing the parameters in the recent past. I'll check later.

**Comment by Glitchy-Tozier** [comment]
>We could consider having a github action that triggers a reeval on push.

That sounds like a great idea!

**Comment by Glitchy-Tozier** [comment]
That being said, the specific implementation might be something that should be thought about.

For example, a commit should probably stop any ongoing re-evaluations and make them start anew.

**Comment by dariogoetz** [comment]
I have implemented a push to heroku followed by a re-evaluation of the layouts upon each push.

**Comment by Glitchy-Tozier** [comment]
Nice job! :)
