### ISSUE TITLE
Prevent reload when enter is pressed on herokuapp

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#20]
Possibly all that is needed is `@submit.stop` to the form, but I'm not sure how to test it out.

```html
    <b-form @submit.stop inline>
        <keyboard-selector @selected="keyboardSelected"></keyboard-selector>
        <b-form-input v-model="filter" debounce="500" placeholder="Filter" class="mb-2 mr-sm-2 mb-sm-0 ml-sm-2"></b-form-input>
        <b-form-checkbox v-model="bestInFamily" class="mb-2 mr-sm-2 mb-sm-0">only show best in family (clears selection)</b-form-checkbox>
      </b-form>
```

**Comment by dariogoetz** [comment]
You can test it by setting up the layouts webservice locally:
1. Install docker.
2. Install docker-compose.
3. Go into the `webui/layouts_webservice` directory and do a `sudo docker-compose up -d`. This starts a postgres database that can be accessed on port 15432.
4. Do a `cargo run --release` to start the server.
5. In a web browser go to http://localhost:8000

However, in this case it will be easier for me to fix it :)
