### ISSUE TITLE
No option to change the letters that should be used for the layout in the webapp

### ISSUE THREAD

**Issue by Gotos** [dariogoetz/keyboard_layout_optimizer#23]
I stumbled over this app while researching how to generate a custom keyboard layout for the way I write. This seems very promising as I can provide my own corpus and I really like the ease of using the webapp for this purpose.

However it seems to me there is no option to generate a layout that doesn't contain Umlauts and ß - which are keys I don't really want to include in my layout.

Is there an option I'm missing to adjust which keys the app will use for the optimization? Or is it possible to add such an option? I think this would benefit people like me who write in different languages from German a lot.

**Comment by dariogoetz** [comment]
## Background
This should be possible by editing a configuration file, but will require some effort. Assuming that you want to optimize for a "standard" keyboard (in contrast to some form of ortholinear/split keyboard), you should start by editing the file `config/standard_keyboard.yml`.

In there, you find a section called `base_layout` and in it `keys`. This is a list (of lists) containing all symbols that can be generated with the keyboard. The order of the keys corresponds to the order seen in the sections above (left to right, then top to bottom). The number of entries in this list needs to coincide with the other sections of the config file. It corresponds to the number of keys on the keyboard.

Each key is represented by a list of symbols corresponding to a layer. The first layer is the "base layer" that is activated by default without holding any modifier key. It usually contains all the characters, numbers and some other useful symbols such as "period" and "comma". The number of layers that can be used is arbitrary. In the section `modifiers`, you can define which keys shall activate each layer (for the left and the right hand).

When specifying a layout to be evaluated by the program, one specifies only a permutation of the base layer, e.g. "zmngx qaupyjß lrstb oeihd fw,cv öäü.k". This permutation takes the `base_layout` and shuffles the keys accordingly. There are two options, though: A symbol in one of the layers can either
1. follow the permutation specified for the base layer or
2. stay at the same position as in the base layer.
Which it is, is defined per layer in the `fixed_layers` section of the config.

## Actual steps to take
Okay, now coming what needs to be done for supporting "non-German" layouts:
Take the `base_layout` -> `keys` section and 
1. remove the Umlaut symbols and `ß`
2. move some other symbols to the place where the Umlauts were
3. check if all the higher layers are to your liking (if you only want to use the base layer and capital letters, make all the lists into length 2)

**Comment by dariogoetz** [comment]
I figured, I might as well do it myself. There is a new config file called `config/standard_keyboard_qwerty.yml` for a simple qwerty layout. Only two layers are present (base layer and capitals). I am not sure if I got all the symbols correctly, please check them.

You can invoke an evaluation using the command:
`cargo run --release -- "qwertyuiop asdfghjkl zxcvbnm,." -l config/standard_keyboard_qwerty.yml`

One note before you do so:
The current configuration for the evaluation metrics puts some restrictions on some Umlauts. These will lead to a crash of the evaluation in the `qwerty` case as these symbols are then unknown. You will need to remove them from the configuration. Look for the section `metrics` -> `asymmetric_keys` -> `params` -> `similar_letters` and comment out the lines with äöü.
It should look like this in the end:
`similar_keys: []`

**Comment by Gotos** [comment]
Cool, thanks for the quick response! I'll check it out at the weekend.

**Comment by Glitchy-Tozier** [comment]
Hi, quick update:
> Look for the section `metrics` -> `asymmetric_keys` -> `params` -> `similar_letters` and comment out the lines with äöü.
It should look like this in the end:
`similar_keys: []`

These are now named differently. If you update your clone, these are the instructions with the new names:

> Look for the section `metrics` -> **`similar_letter_groups`** -> `params` -> **`letter_group_pairs`** and comment out the lines with äöü.
It should look like this in the end:
`letter_group_pairs: []`

**Comment by dariogoetz** [comment]
You are right, thanks for finding out. I fixed the mistakes and renamed the file according to your suggestion. Thanks :)

I have tried to add a US-qwerty as well.

**Comment by dariogoetz** [comment]
Could you check your `config/evaluation/default.yml` if the section `similar_letters` and `similar_letter_groups` contain lists with Umlauts (äöü)? These should be removed as your layout is not able to generate them.

I will see if I can make the corresponding error messages more expressive.

**Comment by krissen** [comment]
I want some of the umlauts, and have edited the file correspondingly. Have revised similar letters etc. from `äöü` to `äö`. (Besides `ä` and `ö` I also want `å`, but figured I won't add that, too, to similar letters, as there already is the a-ä pair.)

**Comment by dariogoetz** [comment]
Sorry. That is not the problem. When reading your error message, I can see that the layout string that the program tries to evaluate `'qwfpbjluyöå arstgmneioä zxcdvkh,.-'` which contains the letter `ä` (after the `o`). Is this a typo on your end or is this some strange behavior?

**Comment by dariogoetz** [comment]
Could you maybe fork the repo and check in your config so I can try to reproduce the issue?

**Comment by krissen** [comment]
> I can see that the layout string that the program tries to evaluate `'qwfpbjluyöå arstgmneioä zxcdvkh,.-'` which contains the letter `ä` (after the `o`). Is this a typo on your end or is this some strange behavior?

Neither typo nor strange behaviour, but as intended. (Swedish umlauts.)

**Comment by krissen** [comment]
> Could you maybe fork the repo and check in your config so I can try to reproduce the issue?

Will do, once back at the keyboard (within an hour or so)!

**Comment by dariogoetz** [comment]
The important thing is that each character that you specify in your "layout string" on the command line (`qwfpbjluyöå arstgmneioä zxcdvkh,.-`) needs to appear as a first entry of the `base_layout` and at the same time the corresponding value in the `fixed_keys` needs to be `false`.

**Comment by krissen** [comment]
The problem was twofold.

> The important thing is that each character that you specify in your "layout string" on the command line (`qwfpbjluyöå arstgmneioä zxcdvkh,.-`) needs to appear as a first entry of the `base_layout`

(1) Some of the keys provided on the primary layer in `base_layout` _weren't_ included in the command line "layout string".

>  and at the same time the corresponding value in the `fixed_keys` needs to be `false`.

(2) A couple of the keys were indeed set to `true`.

Having amended (2), and using the following command line string, it indeed works.
```
cargo run --release -- "<qwfpbjluyöå \$arstgmneioä ^zxcdvkh,.-'" -l config/keyboard/crkbd_colemak_se.yml
```

 Thank you! (Now on to figuring out how to create and use my own corpus.)

**Comment by dariogoetz** [comment]
For providing another corpus, you can
1. use a text-file as corpus directly in the `evaluate` binary using the `-c` option (or a text on the command line with `-t`)
2. pre-compute n-grams with the `ngrams` binary (this is being temporarily performed in the background in the first option above) and then use the so-saved one with the `-n` option of the `evaluate` binary

**Comment by krissen** [comment]
Thank you. Using `-t` with a concatenated text containing pretty much all I've written the past 15 years. Testing with only "unfreezing" some characters, letting most be fixed. Fascinating!
