### ISSUE TITLE
Why is euclidian distance being distorted?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#38]
In two places, we calculate the [euclidian distance](https://www.sciencedirect.com/topics/mathematics/euclidean-distance). However, in both implementations, we distort the result by reducing the horizontal distance. Why is that?

```rs
impl MatrixPosition {
    /// Euclidean distance to another row/column position on the keyboard
    pub fn distance(&self, other: &MatrixPosition) -> f64 {
        (0.5 * (self.0 as f64 - other.0 as f64).powi(2) + (self.1 as f64 - other.1 as f64).powi(2))
            .sqrt()
    }
}
```

```rs
impl Position {
    /// Euclidean distance to another row/column position on the keyboard
    pub fn distance(&self, other: &Position) -> f64 {
        (0.5 * (self.0 - other.0).powi(2) + (self.1 - other.1).powi(2)).sqrt()
    }
}
```

**Comment by dariogoetz** [comment]
That is, indeed, a very good question... Probably a mistake.

**Comment by Glitchy-Tozier** [comment]
Actually … I just checked and it turned out these two methods aren't even used anywhere. At all.

Should I fix them or just remove them?

**Comment by dariogoetz** [comment]
I guess they can be removed, then. Thanks for finding and removing :)
