### ISSUE TITLE
First mention the layout's name in graph.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#4]
For the regular user, doing something like "`bone (shshos sjshsks sdisosbd doxggx xnndd)`" might be easier to read.

![Screenshot_20211116-215911_Firefox Klar.jpg](https://user-images.githubusercontent.com/59611881/142065051-1b531650-2e18-400d-a76d-3635cedd461c.jpg)

**Comment by dariogoetz** [comment]
Has been implemented in f2fb03ffeca886d40dde8f08098f9906114edc10.
