### ISSUE TITLE
Questions regarding `finger_repeats`

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#42]
### `finger_repeats.rs`

Seems like a pretty decent implementation. :)

### `finger_repeats_top_bottom.rs`

1. I might be overlooking something, but it seems like `top_bottom` might be called (and might add a cost) even if the normal `finger_repeats.rs` already was called. Is that what is happening at the moment?
2. The code for this metric is *identical* to the normal `finger_repeats.rs`, the [only differences](https://diffonline.net/dboVpFO58u) being
    - Higher weight in config
    - An additional thumb-rule
Am I correct about the fact that those are the only distinctions?

### `finger_repeats_lateral.rs`

1. Same question as above: This code is called alongside `finger_repeats.rs` and for some reason adds additional costs on top of the "normal" finger_repeats, right?
2. This seems like a fairly downgraded solution compared to the implementation seen in the two other files. Why is that?
3. Why do we want to filter bigrams that start with a thumb (`|| k1.key.finger == Finger::Thumb`) and ignore the ones that end on thumb?
4. Why is this the only metric that has `unbalancing_factor: 1.0`, while every other version uses `0.0`? It seems to me like all the factors should
    1. Should be equal
    2. Should not be on 0 by default (as "factor = 0" implies that the number  will be multiplied by 0 ("0% will be used"))

> 4.

Edit: We actually seem to add 1.0 to every factor, without the user's knowledge. I think it might be better to be transparent, remove the ` 1.0 + ...` and turn the factors from zero to one. Code in question:
```rs
let cost = (1.0 + self.unbalancing_factor * k1.key.unbalancing)
    * (1.0 + self.unbalancing_factor * k2.key.unbalancing)
    * weight;
```

### General

1. We already have a "no increase common bigrams"-setting. Why then do we still increase the weight of common repeats?
```rs
// increase weight of common repeats
if cost > critical_point && total_weight > self.total_weight_threshold {
    cost += (cost - critical_point) * (self.factor - 1.0);
}
```
2. Why do multiple metrics exist "for basically the same thing"? The only reason I can see is that it allows for more detailed evaluation-messages.

**Comment by dariogoetz** [comment]
> ### `finger_repeats.rs`
> 
> Seems like a pretty decent implementation. :)
> ### `finger_repeats_top_bottom.rs`
> 
>     1. I might be overlooking something, but it seems like `top_bottom` might be called (and might add a cost) even if the normal `finger_repeats.rs` already was called. Is that what is happening at the moment?

The `top_bottom` metric adds cost on top of the "usual" `finger_repeats` if the keys are at least two rows apart (columns in case of thumb keys).

> 
>     2. The code for this metric is _identical_ to the normal `finger_repeats.rs`, the [only differences](https://diffonline.net/dboVpFO58u) being
>        
>        * Higher weight in config
>        * An additional thumb-rule
>          Am I correct about the fact that those are the only distinctions?

Yes, but the "thumb-rule" is in fact a rule regarding the horizontal (thumb)/vertical (no-thumb) distance between the keys.

> 
> 
> ### `finger_repeats_lateral.rs`
> 
>     1. Same question as above: This code is called alongside `finger_repeats.rs` and for some reason adds additional costs on top of the "normal" finger_repeats, right?

Yes.

> 
>     2. This seems like a fairly downgraded solution compared to the implementation seen in the two other files. Why is that?

It has no "heritage" from Arnebab's optimizer.

> 
>     3. Why do we want to filter bigrams that start with a thumb (`|| k1.key.finger == Finger::Thumb`) and ignore the ones that end on thumb?

If the fingers are not identical, the cost is 0, see `|| k1.key.finger != k2.key.finger`.


> 
>     4. Why is this the only metric that has `unbalancing_factor: 1.0`, while every other version uses `0.0`? It seems to me like all the factors should
>        
>        1. Should be equal
>        2. Should not be on 0 by default (as "factor = 0" implies that the number  will be multiplied by 0 ("0% will be used"))

To me, moving the hand into an unbalancing position is mostly a lateral movement. Therefore, unbalancing positions hurt lateral finger repeats and not necessarily vertical repeats, where the hand "stays" in the "unbalancing" position.

> 
> 
> > 
> 
> Edit: We actually seem to add 1.0 to every factor, without the user's knowledge. I think it might be better to be transparent, remove the ` 1.0 + ...` and turn the factors from zero to one. Code in question:
> 
> ```rust
> let cost = (1.0 + self.unbalancing_factor * k1.key.unbalancing)
>     * (1.0 + self.unbalancing_factor * k2.key.unbalancing)
>     * weight;
> ```
> 
> ### General
> 
>     1. We already have a "no increase common bigrams"-setting. Why then do we still increase the weight of common repeats?

There are several places where bigram-weights may be increased: For all (common) bigrams and for repeats. One setting influences the one place and the other influences the other. This is legacy from Arnebab's solution.

> 
> 
> ```rust
> // increase weight of common repeats
> if cost > critical_point && total_weight > self.total_weight_threshold {
>     cost += (cost - critical_point) * (self.factor - 1.0);
> }
> ```
> 
>     2. Why do multiple metrics exist "for basically the same thing"? The only reason I can see is that it allows for more detailed evaluation-messages.

This is legacy from Arnebab's solution.

**Comment by Glitchy-Tozier** [comment]
I guess I'll close this issue, since you plan to unify finger repeats sometime in the future.
