### ISSUE TITLE
`total_cost()` returning Option?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#43]
As far as I can tell, not even a single metric has the ability to return `None`.

1. Am I correct about that?
2. If yes, why do we need to wrap our results into an `Option`?

**Comment by dariogoetz** [comment]
It is the `individual_cost` that returns an `Option`. Even though none of the existing metrics do that, it is thinkable that a metric's `total_cost` is not computed as the sum of per-ngram individual costs (but for instance some statistical variance).
The `individual_cost` function, however, is required for the secondary bigrams metric, hence needs to exist for every metric.

**Comment by Glitchy-Tozier** [comment]
Got it
