### ISSUE TITLE
Scale graphs's y-axis to be more informative.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#5]
Some of the shown graphs contain pretty much no information at all.

**Suggestion:** Take all graphs that are less than ...30%..  of the max y-axis value, and plot them on a neighboring second graph.

(That solution may get messy when graphs frequently change size and
need to get re-sorted, though)

![Screenshot_20211116-215849_Firefox Klar.jpg](https://user-images.githubusercontent.com/59611881/142065833-339df1fa-ee1e-442b-8b96-7d47beadd078.jpg)

**Comment by dariogoetz** [comment]
The size of the bars represents the weight with which the individual metric costs are represented in the total cost value. Small bars means that their fraction to the total cost is little. They do not matter much to the total. Having them on a different scale would make interpreting them harder, I believe.
If one is interested in the relative distances between layouts, the "relative barplot" option can be used. If differences are small, the question is why one would be interested in these numbers anyway.

Having a logarithmic y-axis may as an option could make things clearer...

**Comment by dariogoetz** [comment]
> The size of the bars represents the weight with which the individual metric costs are represented in the total cost value. Small bars means that their fraction to the total cost is little. They do not matter much to the total. Having them on a different scale would make interpreting them harder, I believe. If one is interested in the relative distances between layouts, the "relative barplot" option can be used. If differences are small, the question is why one would be interested in these numbers anyway.
> 
> Having a logarithmic y-axis may as an option could make things clearer...

I just tried a logarithmic scale. It does not make things easier to comprehend to me. The layouts only appear much closer to each other.
![image](https://user-images.githubusercontent.com/8102034/142156599-3a63411f-fd87-4134-9c78-849f8b982b97.png)

**Comment by Glitchy-Tozier** [comment]
>The size of the bars represents the weight with which the individual metric costs are represented in the total cost value. Small bars means that their fraction to the total cost is little. They do not matter much to the total. Having them on a different scale would make interpreting them harder, I believe.

Interesting, in that case I agree. If those values don't really matter in the grand scheme of things, it's not that important to show them clearly. It didn't occur to me that the weight already was included in this chart.

> I just tried a logarithmic scale. It does not make things easier to comprehend to me. The layouts only appear much closer to each other.

Personally, I find it interesting to see how even the insignificant values differ. What is your opinion on adding another checkbox to the graph?
- [ ] relative barplot
- [ ] logarithmic scale

**Comment by dariogoetz** [comment]
Has been implemented in 9e22e3643ef5838626d3bed21315bf275af81a7b
