### ISSUE TITLE
Rename "corpus"-directory to "n-grams"

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#50]
There's two reasons for this suggestion:
1. The directory doesn't actually contain any corpora, just the n-grams created from them.
2. The cli-command for specifying n-grams is `--n-grams {location}`, which is nice and intuitive. It seems like a good user-experience to clearly reference those connected things (command & most common location) by using the same name.

**Comment by dariogoetz** [comment]
Good idea. I hope, I didn't break anything.
