### ISSUE TITLE
Key costs

### ISSUE THREAD

**Issue by iandoug** [dariogoetz/keyboard_layout_optimizer#53]
Hi

Was there some formula to determine "key costs" or was it thumb-suck / gut feel?

For example, if I'm reading it correctly, you have same costs for ring/middle/index home keys?

I think I will need to adjust that :-)

**Comment by dariogoetz** [comment]
For the "standard" configs, they are mostly taken from Arnebab's evaluator https://hg.sr.ht/~arnebab/evolve-keyboard-layout/browse/config.py?rev=tip and slightly adjusted by gut feel in a few places.

As this is one of the more personal aspects, all people that contributed to the project mainly have their own config. I use the `crkbd.yml`, [Glitchy-Tozier](https://github.com/Glitchy-Tozier) uses the `ortho.yml`, and [natsume42](https://github.com/natsume42) used the `moonlander.yml`, if I recall correctly.
