### ISSUE TITLE
How to handle " " (space)?

### ISSUE THREAD

**Issue by hpgisler** [dariogoetz/keyboard_layout_optimizer#55]
Hi, I am still experimenting with the 2 x 18 key layout and stumbled over this one (as it is not related to the other discussion, I opened a new one - hope, this is ok).

Suppose, I also want to let the optimizer optimize the position of the `Space` character.
How do I have to enter it in `--fix-from` or `-f` string? (As whitespaces are ignred there.)

(`\ ` does not seem to do the trick.)

**Comment by dariogoetz** [comment]
I added a commandline argument `--do-not-remove-whitespace` to the `plot`, `evaluate`, `optimize_sa`, and `optimize_genetic` binaries. It then considers each whitespace character as a specified symbol for the layout.

**Comment by hpgisler** [comment]
Great! Thank you - works like a charm.
