### ISSUE TITLE
Website optimize include numbers (first row)?

### ISSUE THREAD

**Issue by mlouielu** [dariogoetz/keyboard_layout_optimizer#65]
Hi, thanks for this wonderful project, It helps a lot!

I am trying to see Chewing (bopomofo) cost working on different layout, the problem is we use first row frequently (the most frequent char is 4) but the optimize won't optimize the first row. Is it possible to change this behavior?

The heat map under QWERTY looks like this:

![Selection_2dbf7_2023_07_18_11_19_32](https://github.com/dariogoetz/keyboard_layout_optimizer/assets/28770408/e17be565-e11c-44e6-b1fc-989bb8a03f2a)

Thanks!

**Comment by dariogoetz** [comment]
In the "Keyboard" settings tab, there is a section `fixed_keys`. This section determines which of the keys can be permuted with the string of characters that you provide in the input field. You can set the keys that you want to optimize to `false`, e.g.:
```
  fixed_keys:
    - [ true, false, false, false, false, false, false, false, false, false, false, true,  true,  true]
    - [ true, false, false, false, false, false, false, false, false, false, false, false, false]
    - [ true, false, false, false, false, false, false, false, false, false, false,  true,  true,  true]
    - [ true,  true, false, false, false, false, false, false, false, false, false, false,  true]
    - [ true,  true,  true,                       true,                       true,  true,  true,  true]

```

If you do that, you also need to specify the number keys in the input field, e.g.: `0123456789zyuaqpbmlfjßcsieodtnrhvxüäöwg,.k`

A general advice: If you seriously want to do optimization, it is preferred to not use the website version, but the commandline version. It leverages multi-threading and is much faster.
