### ISSUE TITLE
Cost for layer switching, possible?

### ISSUE THREAD

**Issue by hpgisler** [dariogoetz/keyboard_layout_optimizer#75]
Hi again, 

I've spread the 26 alphas, <space> and hyphen over 2 layers, each layre having 14 keys.

Layer A is activated with MOD-A, Layer B is activated with MOD-B.
Note that an entiery different layre (w/o alphas) is actdive when no MOD is active.

The 2 MODS (A and B) shall have the same cost for activation i.e. switching to (i.e. for the first keypress on that respective layer), but not anymore, when further keypresses on the same layer.

Can I moder this somhow with the existing cost functinos?

**Comment by dariogoetz** [comment]
If I understand your description correctly, you need something like CAPSLOCK behavior (one modifier usage is required for "activating" the layer and subsequent usage of the layer does not involve further modifier usage).

While using the usual "modifier expansion" (or "split modifiers") method, this is a little intricate to implement. There was a pull request with some discussion with @Glitchy-Tozier regarding CAPSLOCK behavior (see #62). In the end, my feeling was that the increase in code complexity would not warrant the effect that one is able to achieve. But there should still be his fork around. You could test that.

If you switch off the modifier expansion functionality (and with it forego proper handling of modifiers for most of the metrics), it would be rather easy to implement a (bigram-) metric that simply counts all occurrences of layer changes and count corresponding modifier costs appropriately.

**Comment by hpgisler** [comment]
Thank you for the link to the PR, good idea..

I am unsure wheter the CAPSLOCK like functionality actually would model the intended cost.
Would the layer switching cost lead to a 2 layer-alphas layout, which would favor keys that are part of high frequency bigrams/trigrams to end up on the same layer?
If that's the case a test of the PR would probably make sense to me...

A small detail:
I would reactivate the respective other layer by holding its individual lock key (i.e. 2 in total) down (release time unimportant).
But a toggling behavior of 1 key (CAPSLOCK style) would model that cost probably just as well...?

**Comment by dariogoetz** [comment]
It is probably not exactly the functionality that you describe, no. Whether it would lead to a layout that you assume is a-priori also not clear. I would guess, though, that it would lead to something like this.

In general, I believe that the optimizer does not really support your use-case (when "modifier expansion" is activated) and the best bet would be the above-mentioned fork.
