### ISSUE TITLE
Replace error-toasts with form-validation

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#8]
A more elegant version than this…

![image](https://user-images.githubusercontent.com/59611881/146395970-f0a41828-a323-44f0-aba1-f5db2768637b.png)

…would be a proper [validation](https://getbootstrap.com/docs/5.0/forms/validation/) of the form-field.

Additionally, showing a `current chars / max chars` at the end or below of the form-field would be great. (`25/32`).

**Comment by dariogoetz** [comment]
I would be happy to accept a pull request for this :)

**Comment by dariogoetz** [comment]
Has been addressed in #b304652d2a000756fa7e6bd4a6a8062bc1392392

**Comment by Glitchy-Tozier** [comment]
Great! The only thing that could still be improved is that the error-message changes the alignment of the elements, I might change that myself at some point in the future. For now, it looks great! :)

![image](https://user-images.githubusercontent.com/59611881/147070925-27a42252-610c-4b41-9276-e21a6fba84c6.png)
![image](https://user-images.githubusercontent.com/59611881/147070983-cd1b8da5-5835-44f2-a7ef-dd99e1cc3f46.png)

**Comment by dariogoetz** [comment]
I noticed that, too. But I was unable to easily change it.
