### ISSUE TITLE
Remove scroll-bars in layout stats

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#9]
Not sure what went wrong, but this doesn't seem ideal:
![image](https://user-images.githubusercontent.com/59611881/146398109-4958651d-54f3-4eaa-b21f-7a9ac55ed6e5.png)

**Comment by dariogoetz** [comment]
Does this still happen after #2660e1cf6912cdc605f3b66129ed492946b134f2?

**Comment by Glitchy-Tozier** [comment]
I re-checked it and now it seems to be working. Closing this issue.
